default['mysql']['test']['Host'] = 'localhost'
default['mysql']['test']['Socket'] = '/var/run/mysqld/mysqld.sock'
default['mysql']['test']['User'] = 'root'
default['mysql']['test']['Password'] = '%password%'
default['mysql']['test']['Database'] = 'testname'
