default["SignalFx_rpm_repo"]["centos"]["7"]["SignalFx-repo"] = "SignalFx-RPMs-centos-7-release-1.0-0.noarch.rpm"
default["SignalFx_rpm_repo"]["centos"]["7"]["SignalFx-repo-link"] = "https://dl.signalfx.com/rpms/SignalFx-rpms/release/SignalFx-RPMs-centos-7-release-1.0-0.noarch.rpm"
default["SignalFx_rpm_repo"]["centos"]["6"]["SignalFx-repo"] = "SignalFx-RPMs-centos-6-release-1.0-0.noarch.rpm"
default["SignalFx_rpm_repo"]["centos"]["6"]["SignalFx-repo-link"] = "https://dl.signalfx.com/rpms/SignalFx-rpms/release/SignalFx-RPMs-centos-6-release-1.0-0.noarch.rpm"
default["SignalFx_rpm_repo"]["centos"]["5"]["SignalFx-repo"] = "SignalFx-RPMs-centos-5-release-1.0-0.noarch.rpm"
default["SignalFx_rpm_repo"]["centos"]["5"]["SignalFx-repo-link"] = "https://s3.amazonaws.com/public-downloads--signalfuse-com/rpms/SignalFx-rpms/release/SignalFx-RPMs-centos-5-release-1.0-0.noarch.rpm"

default["SignalFx_rpm_repo"]["amazon"]["2015.03"]["SignalFx-repo"] = "SignalFx-RPMs-AWS_EC2_Linux_2015_03-release-1.0-0.noarch.rpm"
default["SignalFx_rpm_repo"]["amazon"]["2015.03"]["SignalFx-repo-link"] = "https://dl.signalfx.com/rpms/SignalFx-rpms/release/SignalFx-RPMs-AWS_EC2_Linux_2015_03-release-1.0-0.noarch.rpm"
default["SignalFx_rpm_repo"]["amazon"]["2014.09"]["SignalFx-repo"] = "SignalFx-RPMs-AWS_EC2_Linux_2014_09-release-1.0-0.noarch.rpm"
default["SignalFx_rpm_repo"]["amazon"]["2014.09"]["SignalFx-repo-link"] = "https://dl.signalfx.com/rpms/SignalFx-rpms/release/SignalFx-RPMs-AWS_EC2_Linux_2014_09-release-1.0-0.noarch.rpm"
